# Generated by Django 3.2 on 2021-07-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord_apps_list',
            name='NLP_Model',
            field=models.CharField(blank=True, default='Non ML', max_length=100, null=True),
        ),
    ]
