# Generated by Django 3.2 on 2021-07-30 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord_app', '0002_discord_apps_list_nlp_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLP_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NLP_Model', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='discord_apps_list',
            name='NLP_Model',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discord_app.nlp_models'),
        ),
    ]
