# Generated by Django 3.2 on 2021-07-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord_app', '0003_auto_20210730_1201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='discord_apps_list',
            table='Discord_Apps_List',
        ),
    ]
