# Generated by Django 3.2 on 2021-07-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_app', '0004_alter_discord_apps_list_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nlp_models',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='discord_apps_list',
            name='NLP_Model',
        ),
        migrations.AddField(
            model_name='discord_apps_list',
            name='NLP_Model',
            field=models.ManyToManyField(to='discord_app.NLP_Models'),
        ),
        migrations.AlterModelTable(
            name='nlp_models',
            table='prod_Types',
        ),
    ]
