# Generated by Django 3.2 on 2021-07-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_app', '0005_auto_20210730_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlp_models',
            name='NLP_Model',
            field=models.CharField(default='Non ML', max_length=100, null=True, unique=True),
        ),
    ]
