# Generated by Django 3.2 on 2021-07-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord_app', '0006_alter_nlp_models_nlp_model'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nlp_models',
            table='NLP_Models',
        ),
    ]
