# Generated by Django 3.2 on 2021-07-30 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord_app', '0007_alter_nlp_models_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discord_apps_list',
            name='NLP_Model',
        ),
        migrations.AddField(
            model_name='discord_apps_list',
            name='NLP_Model',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discord_app.nlp_models'),
        ),
    ]
