# Generated by Django 3.2 on 2021-07-30 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord_app', '0008_auto_20210730_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discord_apps_list',
            name='NLP_Model',
            field=models.OneToOneField(default='No Model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discord_app.nlp_models'),
        ),
    ]
